При вызове функции возникло исключение ValueError. Сделали то и то. Продолжаем.
При вызове функции возникло исключение TypeError. Приплыли...
При вызове функции возникло исключение ValueError. Сделали то и то. Продолжаем.
При вызове функции возникло исключение TypeError. Приплыли...
При вызове функции возникло исключение ValueError. Сделали то и то. Продолжаем.
При вызове функции возникло исключение ZeroDivisionError. Сделали то и другое. Продолжаем.
